name: Release on Tag Push

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Extract and Release PDF File on tag push 
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.ref }}

    - name: List Release Releasing Files
      run: |
          ls "${{github.workspace}}/opt3/选必三过教材 参考答案.pdf"

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: ${{ github.ref_name }}
        body: |
          基于标签 ${{ github.ref_name }} 的发布。

          ### 文件详情
          - 选必三过教材 参考答案.pdf
            - 页数：
            - 题数：
            - 字数：
        draft: true
        files: "${{github.workspace}}/opt3/选必三过教材 参考答案.pdf#opt3.pdf"